name = "Modfest: Singularity"
author = "Modfest Organizers and Participants"
version = "0.0.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "511f45bc6e6b10167ac858c402a1700cd2636dfc0e3f7d6607aff0841b95c594"

[versions]
minecraft = "1.19.2"
quilt = "0.17.4"
