name = "Modfest: Singularity"
author = "Modfest Organizers and Participants"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b9cb355713b904c269322bc65af285ea7c94efb9362aca685794df88a111544c"

[versions]
minecraft = "1.19.2"
quilt = "0.17.4"
