name = "Modfest: Singularity"
author = "Modfest Organizers and Participants"
version = "0.0.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d6bbc1e6a8e0d18990705393d9e0c9ab5243b542a95e7f376194dceae344712"

[versions]
minecraft = "1.19.2"
quilt = "0.17.4"
