name = "Modfest: Singularity"
author = "Modfest Organizers and Participants"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "204459d524e38bb0db49dcf4129c4fde47de91cea15d6ce590ae823b410190e3"

[versions]
minecraft = "1.19.2"
quilt = "0.17.4"
