name = "Modfest: Singularity"
author = "Modfest Organizers and Participants"
version = "0.0.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "440a736fc74136a398a9133a193f8be5d642642e03f1b1a7ef436bb7281ae9be"

[versions]
minecraft = "1.19.2"
quilt = "0.17.4"
