name = "Modfest: Singularity"
author = "Modfest Organizers and Participants"
version = "0.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "38c6f7970b184a3677d4feab675249f2dba0dd4967a9de51ed301f57da631617"

[versions]
minecraft = "1.19.2"
quilt = "0.17.4"
